### ISSUE TITLE
[Feature] Add Bookshare as an external source

### ISSUE THREAD

**Issue by dikehprosper** [creativecommons/search#101]
## Problem

With priorities to add a good number of external sources to give users a variety of results from different sources.

## Description
 [Book share](https://www.bookshare.org/cms/search-freely-available) is one such external source with copyright free ebooks available to anyone.

Adding Bookshare as an external source to CC search will be a good addition and will benefit our users.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by bukolamunis** [comment]
iHello, i would like to give this a try, its similar to a task i am rounding up.

**Comment by dikehprosper** [comment]
@bukolamunis thanks ma’am….I already indicated interests

**Comment by bukolamunis** [comment]
> @bukolamunis thanks ma’am….I already indicated my interests tho….Perhaps we can work on it together since you have shown interests too

oh my bad! i didn't know that was you stating interest,yes; i would like to work on it together, would reach out. thanks.

**Comment by possumbilities** [comment]
Can someone offer more details about Bookshare, it seems it operates more as a lending library, and is not a resoruce of CC Licensed materials in any searchable capacity?

**Comment by bukolamunis** [comment]
> Can someone offer more details about Bookshare, it seems it operates more as a lending library, and is not a resource of CC Licensed materials in any searchable capacity?

@dikehprosper if i may;                                                                                                                                                    
 Although its a really good idea, it would not work as a resource to add to CC search engine for a few reasons; 
1. when a book is searched it takes users to a signup page rather than to the book. 
2. Bookshare is a service available only to persons with a Print Disability, either a visual impairment, learning challenge, or physical limitation that prevents them from using traditional print books. 
3. To access books one has to provide proof of disability.
Hi @dikehprosper  what are your other options for electronic book services that don’t have copyright limit, would also research.

**Comment by bukolamunis** [comment]
> @bukolamunis thanks ma’am….I already indicated my interests tho….Perhaps we can work on it together since you have shown interests too

hello, what is your slack handle for communication

**Comment by possumbilities** [comment]
I'm gonna close this, but if you all find a more appropriate engine we could include in this territory you can make a new Feature Issue for it.
