### ISSUE TITLE
[Feature] <Adding A feature called " 'PASF'  'Hot Searches' ">

### ISSUE THREAD

**Issue by Marvisjaja** [creativecommons/search#128]
## Problem
 When  a user clicks on the input to attempt or make a search, most users are left with little or no ideals of the keyword or sets of keywords they want to search. 
![Captureold](https://user-images.githubusercontent.com/115430180/197010832-0cb4235e-5660-48d0-932d-610c1fe0db80.PNG)

## Description
 The search input lacks the feature to bring descriptions on search attempts, adding this feature will improve the user experience on the search section, like when a user clicks on the search input and attempts to make a search, there should be a drop down with the heading and a list "hot search" or a heading "PASF People also search for and a list" when this is available the user gains access to several search options.
![dpjo](https://user-images.githubusercontent.com/115430180/197015495-9024f70f-e8ee-4dd7-96ec-53e0a898b1bf.PNG)

![people-also-search-for-displays-most-often-on-mobile](https://user-images.githubusercontent.com/115430180/197015011-8d83c342-7f71-4d18-8473-d4fe6ae31108.jpg)

## Alternatives
This feature for me is very vital, because search engines appears boring to users if there is no hot search or PASF People also search for. users find search  flexible when this feature is implemented.   

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
Thanks for the work on this contribution! It's an intriguing perspective, but I'm not sure it fits within the intended scope of the CC Search Portal.

Since this is a jumping off point, (a portal), the search queries themselves should not be saved within the site as that would entail a level of data retention and privacy that is largely beyond the scope of this project. 

I agree, that in many instances search engines having the PASF functionality is often useful UX, but in this case the CC Search Portal, is a portal, not an engine itself and it wouldn't have a meaningful reason or method to store past queries in a reasonable manner.
