### ISSUE TITLE
[Bug] Inconsistent HTML Structure  in Search Portal

### ISSUE THREAD

**Issue by Dev-JoyA** [creativecommons/search#230]
## Description
The search portal has an inconsistent HTML structure which affects accessibility and content organization.

## Reproduction
1. Open the repository for the search portal.
2. Compare the HTML structure in the repository with the expected structure outlined in the Vocabulary documentation.
3. Note that the structure is body > header > main instead of the expected body > main > header.

## Expectation
The expected HTML structure should be body > main > header

![Screenshot 2024-10-03 at 10 17 25](https://github.com/user-attachments/assets/882f6509-092d-48c3-bd43-2312c599efe9)

## Environment
Device: Laptop
OS: Windows 10
Browser: Chrome

## Additional context
The implementation of the Vocabulary design system across the Creative Commons web entities has been inconsistent, leading to these structural issues. Addressing them is crucial for ensuring compliance with design standards and enhancing accessibility

## Resolution
- [ ] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
@Dev-JoyA I think some of your formatting didn't come through, it seems like you are referencing tags that aren't in the description of the Issue?

**Comment by Dev-JoyA** [comment]
@possumbilities there is no sidebar region in serach portal so the aside tag is unnecessary, i have edited the bug, and this is the only issue left

**Comment by possumbilities** [comment]
@Dev-JoyA Thank you, I think is ready for work now.

**Comment by FatumaA** [comment]
I'm attempting this

**Comment by possumbilities** [comment]
After reviewing #287 and investigating further I believe this Issue was approved in error. 

I think there might be a misunderstanding about the nature of this sturcture. There are two `header` elements present on most pages utilizing Vocabulary. 

There is the [Header - Global Area](https://vocabulary-docs.netlify.app/#global-header), and there is the [Page Header - Region](https://vocabulary-docs.netlify.app/#page-header-region) itself. Each of these relies on placement within a different context.

I'm closing this Issue and the related PR as the structure does in fact seem to reflect the correct implementation at this time.

**Comment by Dev-JoyA** [comment]
@possumbilities  I totally agree , that was before you explained the concept of the two header to me .
