### ISSUE TITLE
[Bug] Vocabulary css Style rules not followed within the `style.css` file.

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/search#289]
## Description
In the style.css file, the style rule is currently not being followed.
The style rules stated and I quote:

" Style rules are written with two sections
at current, separated by an empty line."

1. First section  for layout, positioning, and related.

2. Second section for visual configuration such
as color, font, background, etc.

E.g:
.selector {
    layout style: rule here

    visual style: rule here
}

## Expectation
Implementing the style rules will enhance code readability and makes it easy for anyone to know where to find what.

- [ ] I would be interested in resolving this bug.

**Comment by possumbilities** [comment]
Originally, I thought this Issue was referring to `vocabulary.css` itself since the two PRs submitted against it addressed that file, so I moved it to the Vocabulary, but in re-triaging it there I realized this Issue is about the `style.css` file within the Search repository and that work here should focus on the `style.css` file and not the `vocabulary.css` file; so I have transferred it back.

**Comment by SumaiyaaRq** [comment]
@possumbilities I have submitted a PR for this issue.
